// services/evaluationDataset.js - 基于实际3GPP文档的评估数据集

// 通信技术问答数据集 - 精确匹配上传的3GPP文档内容
export const telecomQADataset = [
  // ================ 总体架构（20个问题）================
  {
    id: 1,
    question: "NG-RAN的主要组件有哪些？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["UE", "gNB", "5GC", "AMF", "SMF", "UPF"],
    relevant_keywords: ["NG-RAN", "组件", "UE", "gNB", "5GC", "核心网"],
    expected_answer_contains: [
      "用户设备",
      "基站",
      "核心网",
      "接入与移动性管理",
    ],
  },
  {
    id: 2,
    question: "gNB可以拆分为哪些功能单元？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["gNB-CU-CP", "gNB-CU-UP", "gNB-DU"],
    relevant_keywords: ["gNB", "拆分", "CU", "DU", "控制面", "用户面"],
    expected_answer_contains: ["控制面中央单元", "用户面中央单元", "分布单元"],
  },
  {
    id: 3,
    question: "F1接口连接哪两个功能实体？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["F1接口", "CU", "DU", "F1-C", "F1-U"],
    relevant_keywords: ["F1", "接口", "CU", "DU", "控制面", "用户面"],
    expected_answer_contains: ["中央单元", "分布单元", "控制", "用户面"],
  },
  {
    id: 4,
    question: "Xn接口的作用是什么？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["Xn接口", "gNB间互联", "切换", "协同"],
    relevant_keywords: ["Xn", "接口", "gNB", "切换", "协同", "移动性"],
    expected_answer_contains: ["基站之间", "直接互联", "切换效率", "协同"],
  },
  {
    id: 5,
    question: "E1接口连接哪两个实体？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["E1接口", "CU-CP", "CU-UP", "用户面实例"],
    relevant_keywords: ["E1", "CU-CP", "CU-UP", "控制接口"],
    expected_answer_contains: [
      "控制面中央单元",
      "用户面中央单元",
      "用户面实例",
    ],
  },
  {
    id: 6,
    question: "集中+下沉部署形态的设计动机是什么？",
    category: "总体架构",
    difficulty: "advanced",
    expected_concepts: ["集中", "下沉", "时延", "可运维性"],
    relevant_keywords: ["集中", "下沉", "部署", "时延", "运维"],
    expected_answer_contains: [
      "策略功能集中",
      "时序功能下沉",
      "时延",
      "可运维性",
    ],
  },
  {
    id: 7,
    question: "NG接口包含哪两个部分？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["NG接口", "NG-C", "NG-U", "N2", "N3"],
    relevant_keywords: ["NG", "接口", "控制面", "用户面", "N2", "N3"],
    expected_answer_contains: ["控制面", "用户面", "gNB", "5GC"],
  },
  {
    id: 8,
    question: "NG用户平面基于什么协议承载？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["NG用户平面", "GTP-U", "UDP", "IP"],
    relevant_keywords: ["NG", "用户平面", "GTP-U", "隧道", "承载"],
    expected_answer_contains: ["GTP-U", "UDP", "IP", "隧道"],
  },
  {
    id: 9,
    question: "NG控制平面使用什么协议？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["NG控制平面", "NGAP", "AMF"],
    relevant_keywords: ["NG", "控制平面", "NGAP", "AMF", "协议"],
    expected_answer_contains: ["NGAP", "AMF", "接入与移动性"],
  },
  {
    id: 10,
    question: "Xn控制平面使用什么协议？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["Xn控制平面", "XnAP", "上下文转移"],
    relevant_keywords: ["Xn", "控制平面", "XnAP", "协议"],
    expected_answer_contains: ["XnAP", "UE上下文转移", "切换准备"],
  },
  {
    id: 11,
    question: "多无线双连接的定义是什么？",
    category: "总体架构",
    difficulty: "advanced",
    expected_concepts: ["双连接", "Master", "Secondary", "MAC层聚合"],
    relevant_keywords: ["双连接", "多无线", "Master", "Secondary", "聚合"],
    expected_answer_contains: ["两个节点", "MAC层聚合", "Master", "Secondary"],
  },
  {
    id: 12,
    question: "无线接入网共享的目标是什么？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["RAN共享", "运营方", "基础设施", "核心网隔离"],
    relevant_keywords: ["RAN", "共享", "运营方", "基础设施", "隔离"],
    expected_answer_contains: ["多运营方", "共享基础设施", "核心网隔离"],
  },
  {
    id: 13,
    question: "IAB的全称是什么？",
    category: "总体架构",
    difficulty: "beginner",
    expected_concepts: ["IAB", "集成接入和回传", "接入链路", "回传链路"],
    relevant_keywords: [
      "IAB",
      "集成",
      "接入",
      "回传",
      "Integrated Access Backhaul",
    ],
    expected_answer_contains: ["集成接入和回传", "接入链路", "回传链路"],
  },
  {
    id: 14,
    question: "IAB-donor的作用是什么？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["IAB-donor", "锚点", "回传锚定", "拓扑控制"],
    relevant_keywords: ["IAB-donor", "锚点", "gNB", "5GC", "回传"],
    expected_answer_contains: ["锚点", "连接5GC", "回传锚定", "拓扑控制"],
  },
  {
    id: 15,
    question: "IAB-node的功能是什么？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["IAB-node", "接入点", "中继", "层级拓扑"],
    relevant_keywords: ["IAB-node", "接入", "中继", "UE", "回传"],
    expected_answer_contains: ["接入点", "中继", "UE服务", "回传链路"],
  },
  {
    id: 16,
    question: "SNPN和PNI-NPN的区别是什么？",
    category: "总体架构",
    difficulty: "advanced",
    expected_concepts: ["SNPN", "PNI-NPN", "独立", "公网基础设施"],
    relevant_keywords: ["SNPN", "PNI-NPN", "非公网", "PLMN", "切片"],
    expected_answer_contains: [
      "独立非公网",
      "公网基础设施",
      "PLMN标识",
      "核心网",
    ],
  },
  {
    id: 17,
    question: "网络控制的中继器与传统放大器有什么不同？",
    category: "总体架构",
    difficulty: "advanced",
    expected_concepts: ["网络控制", "中继器", "可调度", "可配置"],
    relevant_keywords: ["中继器", "网络控制", "调度", "配置", "放大器"],
    expected_answer_contains: [
      "网络调度",
      "可配置",
      "选择性转发",
      "被动放大器",
    ],
  },
  {
    id: 18,
    question: "CU-CP主要负责哪些功能？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["CU-CP", "RRC", "NAS转发", "安全激活", "移动性"],
    relevant_keywords: ["CU-CP", "RRC", "NAS", "安全", "移动性", "UE上下文"],
    expected_answer_contains: [
      "RRC",
      "NAS转发",
      "安全激活",
      "移动性",
      "UE上下文",
    ],
  },
  {
    id: 19,
    question: "CU-UP主要负责哪些功能？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["CU-UP", "PDCP", "SDAP", "用户面", "QoS流映射"],
    relevant_keywords: ["CU-UP", "PDCP", "SDAP", "用户面", "UPF", "QoS"],
    expected_answer_contains: [
      "PDCP",
      "SDAP",
      "用户面",
      "UPF隧道",
      "QoS流映射",
    ],
  },
  {
    id: 20,
    question: "gNB-DU主要负责哪些功能？",
    category: "总体架构",
    difficulty: "intermediate",
    expected_concepts: ["gNB-DU", "RLC", "MAC", "HARQ", "调度", "L1处理"],
    relevant_keywords: ["DU", "RLC", "MAC", "HARQ", "调度", "PHY", "RU"],
    expected_answer_contains: ["RLC", "MAC", "HARQ", "调度执行", "L1处理"],
  },

  // ================ RRC协议（40个问题）================
  {
    id: 21,
    question: "RRC协议位于哪个平面？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["RRC", "控制面", "Control Plane"],
    relevant_keywords: ["RRC", "控制面", "协议", "UE", "gNB"],
    expected_answer_contains: ["控制面", "UE", "gNB之间"],
  },
  {
    id: 22,
    question: "RRC协议的主要职责包括哪些？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: [
      "系统信息广播",
      "连接控制",
      "测量配置",
      "移动性管理",
      "安全功能",
    ],
    relevant_keywords: ["RRC", "系统信息", "连接", "测量", "移动性", "安全"],
    expected_answer_contains: [
      "系统信息广播",
      "连接控制",
      "测量配置",
      "移动性管理",
    ],
  },
  {
    id: 23,
    question: "系统信息分为哪两大类？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["最小系统信息", "剩余系统信息", "MIB", "SIB1"],
    relevant_keywords: ["系统信息", "MIB", "SIB1", "SIB", "最小", "剩余"],
    expected_answer_contains: ["最小系统信息", "剩余系统信息", "MIB", "SIB1"],
  },
  {
    id: 24,
    question: "RRC连接建立的三个步骤是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: [
      "RRCConnectionRequest",
      "RRCConnectionSetup",
      "RRCConnectionSetupComplete",
    ],
    relevant_keywords: ["RRC连接建立", "Request", "Setup", "Complete", "步骤"],
    expected_answer_contains: [
      "RRCConnectionRequest",
      "RRCConnectionSetup",
      "RRCConnectionSetupComplete",
    ],
  },
  {
    id: 25,
    question: "UE在RRC_IDLE状态下的主要功能有哪些？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["系统信息获取", "小区选择重选", "寻呼接收", "PLMN搜索"],
    relevant_keywords: ["RRC_IDLE", "系统信息", "小区", "寻呼", "PLMN"],
    expected_answer_contains: [
      "系统信息获取",
      "小区选择",
      "寻呼接收",
      "PLMN搜索",
    ],
  },
  {
    id: 26,
    question: "RRC_INACTIVE是NR引入的什么状态？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["RRC_INACTIVE", "新状态", "上下文保留", "快速恢复"],
    relevant_keywords: ["RRC_INACTIVE", "新状态", "NR", "上下文", "快速"],
    expected_answer_contains: ["NR引入", "新状态", "上下文信息", "快速恢复"],
  },
  {
    id: 27,
    question: "RRC_CONNECTED状态的主要特征是什么？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["完整RRC连接", "数据传输", "测量上报", "切换"],
    relevant_keywords: ["RRC_CONNECTED", "连接", "数据传输", "测量", "切换"],
    expected_answer_contains: ["完整RRC连接", "数据传输", "测量上报", "切换"],
  },
  {
    id: 28,
    question: "RRC消息分为哪几大类？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: [
      "系统信息消息",
      "连接控制消息",
      "重建消息",
      "测量消息",
      "安全消息",
    ],
    relevant_keywords: [
      "RRC消息",
      "系统信息",
      "连接控制",
      "重建",
      "测量",
      "安全",
    ],
    expected_answer_contains: [
      "系统信息",
      "连接控制",
      "重建",
      "测量配置",
      "安全控制",
    ],
  },
  {
    id: 29,
    question: "MIB提供什么信息？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["MIB", "主信息块", "基本同步", "物理层配置"],
    relevant_keywords: ["MIB", "主信息块", "同步", "物理层", "配置"],
    expected_answer_contains: ["主信息块", "基本同步", "物理层配置"],
  },
  {
    id: 30,
    question: "SIBs提供什么类型的信息？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: [
      "SIBs",
      "系统信息块",
      "小区接入",
      "公共信道",
      "网络参数",
    ],
    relevant_keywords: ["SIB", "系统信息块", "小区", "接入", "信道", "参数"],
    expected_answer_contains: [
      "系统信息块",
      "小区接入",
      "公共信道",
      "网络参数",
    ],
  },
  {
    id: 31,
    question: "RRC连接重建适用于什么场景？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["无线链路失败", "RLF", "Handover失败", "连接恢复"],
    relevant_keywords: ["RRC重建", "RLF", "链路失败", "Handover", "恢复"],
    expected_answer_contains: ["无线链路失败", "RLF", "Handover失败"],
  },
  {
    id: 32,
    question: "RRC与NAS层是什么关系？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["RRC", "NAS", "中继层", "透明传输", "SRB"],
    relevant_keywords: ["RRC", "NAS", "中继", "透明", "SRB", "核心网"],
    expected_answer_contains: ["中继层", "透明传输", "不改变NAS消息"],
  },
  {
    id: 33,
    question: "RRC如何为不同层提供配置？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["PDCP", "RLC", "MAC", "PHY", "配置参数", "动态修改"],
    relevant_keywords: ["RRC", "PDCP", "RLC", "MAC", "PHY", "配置"],
    expected_answer_contains: ["配置参数", "承载映射", "调度策略", "动态修改"],
  },
  {
    id: 34,
    question: "RRC连接释放后UE进入什么状态？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["连接释放", "RRC_IDLE", "RRC_INACTIVE"],
    relevant_keywords: ["连接释放", "RRC_IDLE", "RRC_INACTIVE", "状态"],
    expected_answer_contains: ["RRC_IDLE", "RRC_INACTIVE"],
  },
  {
    id: 35,
    question: "系统信息获取的过程是怎样的？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["MIB", "基本同步", "SIB1", "小区接入", "其余SIBs"],
    relevant_keywords: ["系统信息", "获取", "MIB", "SIB1", "同步", "接入"],
    expected_answer_contains: [
      "MIB获取基本同步",
      "SIB1确定接入参数",
      "其余SIBs按需获取",
    ],
  },
  {
    id: 36,
    question: "RRC如何支持5G SA与NSA部署？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["5G SA", "NSA", "EN-DC", "NR与LTE协调"],
    relevant_keywords: ["RRC", "5G SA", "NSA", "EN-DC", "LTE", "协调"],
    expected_answer_contains: ["EN-DC模式", "NR与LTE", "协调"],
  },
  {
    id: 37,
    question: "RRC如何支持网络切片？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["网络切片", "UE切片绑定", "S-NSSAI", "承载配置"],
    relevant_keywords: ["RRC", "网络切片", "S-NSSAI", "绑定", "承载"],
    expected_answer_contains: ["UE与切片绑定", "S-NSSAI参数", "承载配置"],
  },
  {
    id: 38,
    question: "RRC测量配置的目的是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["测量配置", "邻小区", "信号质量", "切换", "负载均衡"],
    relevant_keywords: ["RRC", "测量", "配置", "邻小区", "切换", "负载"],
    expected_answer_contains: [
      "邻小区信号质量",
      "切换",
      "负载均衡",
      "覆盖优化",
    ],
  },
  {
    id: 39,
    question: "UE测量报告的触发方式有哪些？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["定期", "事件触发", "测量结果", "上报"],
    relevant_keywords: ["测量报告", "定期", "事件", "触发", "UE"],
    expected_answer_contains: ["定期", "事件触发地上报"],
  },
  {
    id: 40,
    question: "RRC安全功能包括哪些？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["密钥传递", "安全激活", "加密", "完整性保护"],
    relevant_keywords: ["RRC", "安全", "密钥", "加密", "完整性"],
    expected_answer_contains: ["密钥传递", "安全激活", "加密", "完整性保护"],
  },
  {
    id: 41,
    question: "RRC如何进行QoS控制？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["PDU Session", "QoS Flow", "DRB", "QoS参数"],
    relevant_keywords: ["RRC", "QoS", "DRB", "PDU Session", "QoS Flow"],
    expected_answer_contains: ["建立DRB", "QoS参数配置", "差异化需求"],
  },
  {
    id: 42,
    question: "UE能力管理的作用是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["UE能力", "功能支持", "频段", "CA", "MIMO", "调度策略"],
    relevant_keywords: ["UE能力", "功能", "频段", "CA", "MIMO", "QoS"],
    expected_answer_contains: ["上报支持功能", "调度与配置策略"],
  },
  {
    id: 43,
    question: "RRC如何支持Intra-NR协作？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: [
      "Intra-NR",
      "Inter-RAT",
      "LTE",
      "NB-IoT",
      "Wi-Fi",
      "互操作",
    ],
    relevant_keywords: ["RRC", "Intra-NR", "Inter-RAT", "LTE", "互操作"],
    expected_answer_contains: ["异构网络", "互操作能力", "跨RAT测量"],
  },
  {
    id: 44,
    question: "RRC_INACTIVE状态的应用场景是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["高频数据", "间歇业务", "IoT", "低时延", "低功耗"],
    relevant_keywords: ["RRC_INACTIVE", "间歇", "IoT", "低时延", "低功耗"],
    expected_answer_contains: ["高频数据间歇业务", "IoT低时延", "低功耗场景"],
  },
  {
    id: 45,
    question: "RRC连接建立完成后会建立哪些承载？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["SRB0", "SRB1", "UE上下文", "安全过程"],
    relevant_keywords: ["RRC连接", "SRB0", "SRB1", "承载", "安全"],
    expected_answer_contains: ["SRB0", "SRB1", "UE上下文", "安全过程"],
  },
  {
    id: 46,
    question: "小区选择和重选分别适用于什么模式？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: [
      "小区选择",
      "小区重选",
      "Idle模式",
      "Connected模式",
      "切换",
    ],
    relevant_keywords: ["小区选择", "重选", "Idle", "Connected", "切换"],
    expected_answer_contains: [
      "小区选择/重选",
      "Idle模式",
      "切换",
      "Connected模式",
    ],
  },
  {
    id: 47,
    question: "SecurityModeCommand消息的作用是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["SecurityModeCommand", "密钥", "安全上下文", "建立"],
    relevant_keywords: ["SecurityModeCommand", "安全", "密钥", "上下文"],
    expected_answer_contains: ["密钥", "安全上下文建立"],
  },
  {
    id: 48,
    question: "UE-CapabilityEnquiry消息用于什么目的？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: [
      "UE-CapabilityEnquiry",
      "UE能力",
      "查询",
      "Information",
    ],
    relevant_keywords: ["UE-CapabilityEnquiry", "能力", "查询", "Information"],
    expected_answer_contains: ["UE能力", "查询", "上报"],
  },
  {
    id: 49,
    question: "RRC重建立的步骤是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["ReestablishmentRequest", "判定恢复", "RRC_CONNECTED"],
    relevant_keywords: ["RRC重建", "ReestablishmentRequest", "恢复", "步骤"],
    expected_answer_contains: [
      "ReestablishmentRequest",
      "判定是否允许恢复",
      "恢复RRC_CONNECTED",
    ],
  },
  {
    id: 50,
    question: "RRC协议如何实现跨RAT切换？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["跨RAT", "切换", "测量配置", "管理"],
    relevant_keywords: ["RRC", "跨RAT", "切换", "测量", "管理"],
    expected_answer_contains: ["跨RAT测量", "切换", "配置和管理"],
  },
  {
    id: 51,
    question: "MeasurementControl消息的功能是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["MeasurementControl", "测量配置", "网络优化"],
    relevant_keywords: ["MeasurementControl", "测量", "配置", "网络"],
    expected_answer_contains: ["测量配置", "网络优化"],
  },
  {
    id: 52,
    question: "MeasurementReport消息包含什么信息？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["MeasurementReport", "测量结果", "移动性"],
    relevant_keywords: ["MeasurementReport", "测量", "结果", "移动性"],
    expected_answer_contains: ["测量结果", "移动性"],
  },
  {
    id: 53,
    question: "RRC如何参与网络切片选择？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["网络切片", "S-NSSAI", "选择", "NG-RAN管理"],
    relevant_keywords: ["RRC", "网络切片", "S-NSSAI", "选择", "NG-RAN"],
    expected_answer_contains: ["网络切片", "S-NSSAI", "选择"],
  },
  {
    id: 54,
    question: "RRC与gNB-CU/DU架构如何协同？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["gNB-CU", "DU架构", "协同", "集中分布式控制"],
    relevant_keywords: ["RRC", "gNB-CU", "DU", "架构", "协同"],
    expected_answer_contains: ["gNB-CU/DU架构", "协同", "集中/分布式控制"],
  },
  {
    id: 55,
    question: "RRC状态迁移的触发条件有哪些？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: [
      "状态迁移",
      "RRC_IDLE",
      "RRC_INACTIVE",
      "RRC_CONNECTED",
      "触发条件",
    ],
    relevant_keywords: ["RRC状态", "迁移", "触发", "条件"],
    expected_answer_contains: ["连接建立", "释放", "寻呼", "业务需求"],
  },
  {
    id: 56,
    question: "RRC协议如何支持多RAT协作？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["多RAT协作", "LTE", "NR", "WLAN", "互操作"],
    relevant_keywords: ["RRC", "多RAT", "协作", "LTE", "WLAN"],
    expected_answer_contains: ["LTE", "NR", "WLAN", "互操作"],
  },
  {
    id: 57,
    question: "RRC消息中的承载管理消息作用是什么？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["承载管理", "SRB", "DRB", "建立释放", "PDU Session"],
    relevant_keywords: ["承载管理", "SRB", "DRB", "建立", "释放"],
    expected_answer_contains: ["SRB", "DRB建立与释放", "PDU Session"],
  },
  {
    id: 58,
    question: "RRC协议的设计目标是什么？",
    category: "RRC",
    difficulty: "beginner",
    expected_concepts: ["灵活性", "高效性", "多样化业务", "复杂网络部署"],
    relevant_keywords: ["RRC", "设计目标", "灵活性", "高效性", "业务"],
    expected_answer_contains: [
      "灵活性",
      "高效性",
      "多样化业务需求",
      "复杂网络部署",
    ],
  },
  {
    id: 59,
    question: "初始接入时UE如何获取系统信息？",
    category: "RRC",
    difficulty: "intermediate",
    expected_concepts: ["初始接入", "MIB", "基本同步", "SIB1", "小区接入"],
    relevant_keywords: ["初始接入", "MIB", "SIB1", "系统信息", "获取"],
    expected_answer_contains: ["MIB获取基本同步", "SIB1确定小区接入参数"],
  },
  {
    id: 60,
    question: "RRC层如何保证信令的可靠性？",
    category: "RRC",
    difficulty: "advanced",
    expected_concepts: ["SRB", "优先级", "重传策略", "可靠性", "完整性保护"],
    relevant_keywords: ["RRC", "信令", "可靠性", "SRB", "重传"],
    expected_answer_contains: ["SRB服务", "优先级", "重传策略", "可靠性"],
  },

  // ================ QoS服务质量（10个问题）================
  {
    id: 61,
    question: "QoS在5G系统中的核心作用是什么？",
    category: "QoS",
    difficulty: "beginner",
    expected_concepts: ["QoS", "差异化服务", "传输优先级", "可靠性保障"],
    relevant_keywords: ["QoS", "服务质量", "差异化", "优先级", "可靠性"],
    expected_answer_contains: ["差异化服务", "传输优先级", "可靠性保障"],
  },
  {
    id: 62,
    question: "5G QoS架构的关键要素有哪些？",
    category: "QoS",
    difficulty: "intermediate",
    expected_concepts: ["QoS流", "QoS规则", "QoS参数", "映射关系"],
    relevant_keywords: ["QoS架构", "QoS流", "QoS规则", "参数", "映射"],
    expected_answer_contains: ["QoS流", "QoS规则", "QoS参数", "映射关系"],
  },
  {
    id: 63,
    question: "QoS流由什么标识符标识？",
    category: "QoS",
    difficulty: "beginner",
    expected_concepts: ["QoS流", "QFI", "QoS Flow Identifier"],
    relevant_keywords: ["QoS流", "QFI", "标识符", "Identifier"],
    expected_answer_contains: ["QFI", "QoS Flow Identifier"],
  },
  {
    id: 64,
    question: "5QI的作用是什么？",
    category: "QoS",
    difficulty: "intermediate",
    expected_concepts: ["5QI", "5G QoS Identifier", "QoS特性", "默认参数"],
    relevant_keywords: ["5QI", "标识符", "QoS特性", "参数"],
    expected_answer_contains: ["5G QoS Identifier", "QoS特性", "默认参数"],
  },
  {
    id: 65,
    question: "GBR和Non-GBR的区别是什么？",
    category: "QoS",
    difficulty: "intermediate",
    expected_concepts: ["GBR", "Non-GBR", "保证比特率", "带宽保障"],
    relevant_keywords: ["GBR", "Non-GBR", "比特率", "带宽", "保障"],
    expected_answer_contains: ["保证比特率", "带宽保障", "互联网数据"],
  },
  {
    id: 66,
    question: "Delay Critical GBR适用于什么业务？",
    category: "QoS",
    difficulty: "advanced",
    expected_concepts: ["Delay Critical GBR", "URLLC", "极低时延", "可靠性"],
    relevant_keywords: ["Delay Critical", "GBR", "URLLC", "时延", "可靠性"],
    expected_answer_contains: ["URLLC", "极低时延", "可靠性99.999%"],
  },
  {
    id: 67,
    question: "QoS处理的核心网侧流程是怎样的？",
    category: "QoS",
    difficulty: "advanced",
    expected_concepts: ["SMF", "PCF", "UPF", "策略配置", "QoS规则"],
    relevant_keywords: ["核心网", "SMF", "PCF", "UPF", "策略", "规则"],
    expected_answer_contains: [
      "SMF决定QoS规则",
      "PCF策略决策",
      "UPF数据包映射",
    ],
  },
  {
    id: 68,
    question: "MAC层如何实现QoS调度？",
    category: "QoS",
    difficulty: "advanced",
    expected_concepts: [
      "优先级调度",
      "动态资源分配",
      "多队列调度",
      "切片级调度",
    ],
    relevant_keywords: ["MAC", "调度", "优先级", "资源", "队列"],
    expected_answer_contains: ["优先级调度", "动态资源分配", "多队列调度"],
  },
  {
    id: 69,
    question: "ARP的作用是什么？",
    category: "QoS",
    difficulty: "intermediate",
    expected_concepts: ["ARP", "分配与保持优先级", "资源紧张", "建立保持"],
    relevant_keywords: ["ARP", "优先级", "资源", "建立", "保持"],
    expected_answer_contains: ["分配与保持优先级", "资源紧张", "建立/保持"],
  },
  {
    id: 70,
    question: "QoS策略控制由哪个网络功能决策？",
    category: "QoS",
    difficulty: "intermediate",
    expected_concepts: ["PCF", "Policy Control Function", "SMF执行"],
    relevant_keywords: ["QoS策略", "PCF", "Policy Control", "SMF"],
    expected_answer_contains: ["PCF", "Policy Control Function", "SMF执行"],
  },

  // ================ 功能分离（10个问题）================
  {
    id: 71,
    question: "功能分离的基本设计原则是什么？",
    category: "功能分离",
    difficulty: "beginner",
    expected_concepts: ["模块化", "可组合性", "解耦", "灵活部署"],
    relevant_keywords: ["功能分离", "模块化", "解耦", "灵活", "部署"],
    expected_answer_contains: ["模块化", "解耦", "灵活部署"],
  },
  {
    id: 72,
    question: "CU主要负责哪些功能？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["CU", "非实时", "高层功能", "RRC", "PDCP", "QoS管理"],
    relevant_keywords: ["CU", "中央单元", "RRC", "PDCP", "QoS"],
    expected_answer_contains: ["非实时", "RRC", "PDCP", "QoS管理", "NG接口"],
  },
  {
    id: 73,
    question: "DU主要负责哪些功能？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["DU", "实时性", "RLC", "MAC", "PHY层", "调度"],
    relevant_keywords: ["DU", "分布式单元", "RLC", "MAC", "PHY", "调度"],
    expected_answer_contains: ["实时性", "RLC", "MAC", "PHY层", "调度"],
  },
  {
    id: 74,
    question: "F1接口分为哪两个部分？",
    category: "功能分离",
    difficulty: "beginner",
    expected_concepts: ["F1接口", "F1-C", "F1-U", "控制面", "用户面"],
    relevant_keywords: ["F1", "接口", "F1-C", "F1-U", "控制", "用户"],
    expected_answer_contains: ["F1-C", "F1-U", "控制面", "用户面"],
  },
  {
    id: 75,
    question: "RU的主要功能是什么？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["RU", "射频功能", "收发", "DAC", "ADC", "放大器"],
    relevant_keywords: ["RU", "射频", "Radio Unit", "收发", "放大器"],
    expected_answer_contains: ["射频", "信号收发", "数模转换", "放大器"],
  },
  {
    id: 76,
    question: "高层分离适合什么场景？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["高层分离", "CU/DU分离", "低时延", "灵活部署"],
    relevant_keywords: ["高层分离", "CU/DU", "时延", "灵活", "部署"],
    expected_answer_contains: ["PDCP及以上功能集中", "低时延要求", "灵活部署"],
  },
  {
    id: 77,
    question: "低层分离对传输网络有什么要求？",
    category: "功能分离",
    difficulty: "advanced",
    expected_concepts: ["低层分离", "DU/RU", "前传", "带宽", "时延"],
    relevant_keywords: ["低层分离", "DU/RU", "前传", "带宽", "时延"],
    expected_answer_contains: ["前传链路", "带宽", "时延", "极高要求"],
  },
  {
    id: 78,
    question: "功能分离的优点有哪些？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["灵活部署", "降低成本", "云化", "差异化需求"],
    relevant_keywords: ["功能分离", "优点", "灵活", "成本", "云化"],
    expected_answer_contains: ["灵活部署", "降低CAPEX", "云化", "差异化需求"],
  },
  {
    id: 79,
    question: "功能分离的缺点有哪些？",
    category: "功能分离",
    difficulty: "intermediate",
    expected_concepts: ["传输网络要求", "运维复杂", "跨厂商互通"],
    relevant_keywords: ["功能分离", "缺点", "传输", "运维", "互通"],
    expected_answer_contains: ["传输网络要求高", "运维复杂度", "跨厂商互通"],
  },
  {
    id: 80,
    question: "云RAN部署对传输网络的要求最苛刻的是什么？",
    category: "功能分离",
    difficulty: "advanced",
    expected_concepts: ["云RAN", "更细粒度分离", "FFT", "IFFT", "MIMO预编码"],
    relevant_keywords: ["云RAN", "细粒度", "分离", "FFT", "MIMO"],
    expected_answer_contains: [
      "更细粒度的分离",
      "PHY层内部",
      "传输网络要求最苛刻",
    ],
  },

  // ================ 协议流程（20个问题）================
  {
    id: 81,
    question: "UE初始接入的第一步是什么？",
    category: "协议流程",
    difficulty: "beginner",
    expected_concepts: ["随机接入", "RACH", "Random Access Procedure"],
    relevant_keywords: ["初始接入", "随机接入", "RACH", "UE"],
    expected_answer_contains: ["随机接入过程", "RACH", "建立同步"],
  },
  {
    id: 82,
    question: "初始上下文建立涉及哪些网元？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["AMF", "gNB", "NGAP", "安全上下文", "PDU会话"],
    relevant_keywords: ["初始上下文", "AMF", "gNB", "NGAP", "建立"],
    expected_answer_contains: ["AMF", "gNB", "NGAP消息", "安全上下文"],
  },
  {
    id: 83,
    question: "注册过程中UE需要向AMF发送什么信息？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["注册请求", "身份标识", "5G-GUTI", "SUCI"],
    relevant_keywords: ["注册", "UE", "AMF", "身份", "5G-GUTI", "SUCI"],
    expected_answer_contains: ["注册请求", "身份标识", "5G-GUTI", "SUCI"],
  },
  {
    id: 84,
    question: "鉴权过程涉及哪些网络功能？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["AMF", "AUSF", "鉴权向量", "AKA协议"],
    relevant_keywords: ["鉴权", "AMF", "AUSF", "Authentication", "AKA"],
    expected_answer_contains: ["AMF", "AUSF", "鉴权向量", "AKA协议"],
  },
  {
    id: 85,
    question: "PDU会话建立的流程包括哪些步骤？",
    category: "协议流程",
    difficulty: "advanced",
    expected_concepts: ["UE请求", "SMF分配", "UPF隧道", "DRB配置"],
    relevant_keywords: ["PDU会话", "建立", "SMF", "UPF", "DRB"],
    expected_answer_contains: ["UE请求", "SMF分配", "UPF建立隧道", "DRB配置"],
  },
  {
    id: 86,
    question: "切换流程的触发条件是什么？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["信号质量下降", "目标小区", "优质量", "源gNB"],
    relevant_keywords: ["切换", "触发", "信号质量", "小区", "gNB"],
    expected_answer_contains: ["信号质量下降", "目标小区提供更优质量"],
  },
  {
    id: 87,
    question: "切换过程中如何保证业务不中断？",
    category: "协议流程",
    difficulty: "advanced",
    expected_concepts: ["UPF", "路径切换", "Path Switch", "业务连续"],
    relevant_keywords: ["切换", "业务", "中断", "UPF", "Path Switch"],
    expected_answer_contains: ["UPF", "路径切换", "Path Switch", "业务不中断"],
  },
  {
    id: 88,
    question: "上下文释放的触发场景有哪些？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["闲置态", "无业务", "切换失败", "Context Release"],
    relevant_keywords: ["上下文释放", "闲置", "业务", "切换失败"],
    expected_answer_contains: ["闲置态", "无业务活动", "切换失败"],
  },
  {
    id: 89,
    question: "UE去注册过程会删除什么上下文？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["去注册", "SMF", "UPF", "会话上下文"],
    relevant_keywords: ["去注册", "SMF", "UPF", "上下文", "删除"],
    expected_answer_contains: ["SMF/UPF", "会话上下文", "删除"],
  },
  {
    id: 90,
    question: "QoS流建立时SMF的作用是什么？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["SMF", "QoS流", "5QI", "分配", "映射"],
    relevant_keywords: ["QoS流", "SMF", "建立", "5QI", "分配"],
    expected_answer_contains: ["SMF分配", "QoS流", "5QI", "映射"],
  },
  {
    id: 91,
    question: "QoS流修改的触发原因有哪些？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["策略变化", "UPF路径", "SMF发起"],
    relevant_keywords: ["QoS流", "修改", "策略", "UPF", "路径"],
    expected_answer_contains: ["策略变化", "UPF路径变化", "SMF发起"],
  },
  {
    id: 92,
    question: "RRC重建立适用于什么异常场景？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["链路失败", "RLF", "UE上下文丢失", "重建立"],
    relevant_keywords: ["RRC重建", "链路失败", "RLF", "上下文"],
    expected_answer_contains: ["链路失败", "RLF", "UE上下文丢失"],
  },
  {
    id: 93,
    question: "异常恢复机制的目标是什么？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["保持注册", "业务连续性", "中断恢复"],
    relevant_keywords: ["异常恢复", "注册", "业务连续", "中断"],
    expected_answer_contains: ["保持UE注册状态", "业务连续性"],
  },
  {
    id: 94,
    question: "切换命令由哪个网元发送？",
    category: "协议流程",
    difficulty: "beginner",
    expected_concepts: ["源gNB", "切换命令", "RRC", "UE"],
    relevant_keywords: ["切换命令", "源gNB", "RRC", "UE"],
    expected_answer_contains: ["源gNB", "RRC", "切换命令"],
  },
  {
    id: 95,
    question: "UE完成切换后需要做什么？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["接入目标gNB", "RRC重配置", "上下文更新"],
    relevant_keywords: ["切换", "目标gNB", "RRC重配置", "上下文"],
    expected_answer_contains: ["接入目标gNB", "RRC重配置", "上下文更新"],
  },
  {
    id: 96,
    question: "安全上下文建立使用什么协议？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["NAS Security Mode", "加密算法", "完整性保护"],
    relevant_keywords: ["安全上下文", "NAS", "Security Mode", "加密"],
    expected_answer_contains: ["NAS Security Mode", "加密算法", "完整性保护"],
  },
  {
    id: 97,
    question: "协议流程覆盖了UE生命周期的哪些阶段？",
    category: "协议流程",
    difficulty: "beginner",
    expected_concepts: ["接入", "注册", "鉴权", "会话管理", "切换", "释放"],
    relevant_keywords: ["协议流程", "生命周期", "接入", "注册", "切换"],
    expected_answer_contains: [
      "接入",
      "注册",
      "鉴权",
      "会话管理",
      "切换",
      "释放",
    ],
  },
  {
    id: 98,
    question: "初始UE消息的作用是什么？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["初始UE消息", "gNB", "AMF", "身份标识", "接入请求"],
    relevant_keywords: ["初始UE消息", "gNB", "AMF", "身份", "接入"],
    expected_answer_contains: ["gNB向AMF", "身份标识", "接入请求信息"],
  },
  {
    id: 99,
    question: "PDU会话资源建立请求由哪个网元发起？",
    category: "协议流程",
    difficulty: "intermediate",
    expected_concepts: ["AMF", "NGAP", "gNB", "PDU Session Resource Setup"],
    relevant_keywords: ["PDU会话", "资源建立", "AMF", "NGAP", "gNB"],
    expected_answer_contains: ["AMF", "NGAP", "gNB", "PDU会话资源建立请求"],
  },
  {
    id: 100,
    question: "协议流程依赖的核心网功能分工是什么？",
    category: "协议流程",
    difficulty: "advanced",
    expected_concepts: ["AMF控制", "SMF会话", "UPF转发", "分工合作"],
    relevant_keywords: ["协议流程", "AMF", "SMF", "UPF", "分工"],
    expected_answer_contains: ["AMF控制", "SMF会话", "UPF转发", "分工合作"],
  },
];

// 改进的随机采样函数，确保类别分布均匀
export const sampleDataset = (sampleSize) => {
  const categories = ["总体架构", "RRC", "QoS", "功能分离", "协议流程"];
  const totalQuestions = telecomQADataset.length;
  let result = [];

  categories.forEach((category) => {
    const categoryQuestions = telecomQADataset.filter(
      (q) => q.category === category
    );
    const categoryRatio = categoryQuestions.length / totalQuestions;
    const categorySize = Math.max(1, Math.round(sampleSize * categoryRatio));

    const shuffled = [...categoryQuestions].sort(() => 0.5 - Math.random());
    result = result.concat(shuffled.slice(0, categorySize));
  });

  return result.sort(() => 0.5 - Math.random());
};

// 数据集统计信息
export const datasetStats = {
  totalQuestions: telecomQADataset.length,
  categories: {
    总体架构: telecomQADataset.filter((q) => q.category === "总体架构").length,
    RRC: telecomQADataset.filter((q) => q.category === "RRC").length,
    QoS: telecomQADataset.filter((q) => q.category === "QoS").length,
    功能分离: telecomQADataset.filter((q) => q.category === "功能分离").length,
    协议流程: telecomQADataset.filter((q) => q.category === "协议流程").length,
  },
  difficulties: {
    beginner: telecomQADataset.filter((q) => q.difficulty === "beginner")
      .length,
    intermediate: telecomQADataset.filter(
      (q) => q.difficulty === "intermediate"
    ).length,
    advanced: telecomQADataset.filter((q) => q.difficulty === "advanced")
      .length,
  },
};
